theme: minima
title: Christopher Bonhage
author: Christopher Bonhage
email: me@christopherbonhage.com
github_username: meeq
google_analytics: UA-101038319-1
header_pages:
  - title: Home
    url: '/'
  - title: Posts
    url: '/posts'
  - title: Î¼blog
    url: '/microblog'
  - title: Resume
    url: '/resume'
